name: Execute Maintenance Resume

on:
  workflow_dispatch:
    inputs:
      env_id:
        description: "Environment ID (e.g., prd, stg1, dev01...)"
        required: true
  schedule:
    - cron: "10 16 * * *"

jobs:
  execute_resume:
    runs-on: ${{ (github.event_name == 'schedule' || inputs.env_id == 'prd' || inputs.env_id == 'stg1') && 'cicd-dev' || 'cicd-prd' }}
    env:
      REF: ${{ (github.event_name == 'schedule' || inputs.env_id == 'prd' || inputs.env_id == 'stg1') && 'main' || 'develop'
      TARGET_ENV_ID: ${{ github.event_name == 'schedule' && 'prd' || inputs.env_id }}

    steps:
      - name: Execute workflow Maintenance Resume
        run: |
          echo "${{ env.REF }}"
          echo "${{ env.TARGET_ENV_ID }}"
